### ISSUE TITLE
Animator.shared is problematic on macOS with multiple displays

### ISSUE THREAD

**Issue by jessegrosjean** [b3ll/Motion#18]
I don't propose a fix at this point, but figure I should add here so problem is remembered.

The issue is that if you have two displays then a single display link won't work optimally since they will have a different vsync. The current code uses `CVDisplayLinkCreateWithActiveCGDisplays` to create a generic displaylink that will work in this case, but it's (at least in some cases) using just a timer instead of direct connection to vsync. So missing most display link benefits.

More info here:

https://thume.ca/2017/12/09/cvdisplaylink-doesnt-link-to-your-display/

I guess to handle this case Motion needs to be changed so that clients can use multiple Animators and pick which one they want depending on which display window is in. My code isn't ready to handle that yet, and will require some modifications to Motion.

**Comment by b3ll** [comment]
Yeah this has always been a worry for me on macOS, I don't know of any real fixes other than yeah, having multiple animators. It would make Motion a bit more cumbersome to use (having to worry your Animator is setup correctly, vs. just firing off a spring), but maybe that's an OK tradeoff for macOS.

**Comment by insidegui** [comment]
Since everything on macOS always happens in a window, I think the library could provide a means for the user to attach a given animation to a window. The library would then make sure that the display link driving such animation corresponds to the screen where the window is currently at. I'll see if I can put something together in my fork 😄

**Comment by b3ll** [comment]
This should now be addressed. Thanks @insidegui
