### ISSUE TITLE
Invalid `CAFrameRateRange` in `CoreAnimationDriver`

### ISSUE THREAD

**Issue by adamastern** [b3ll/Motion#25]
An iPhone 11 Pro is reporting its `UIScreen.maximumFramesPerSecond` as `61`, which leads to `CoreAnimationDriver` creating an invalid `CAFrameRateRange` [here](https://github.com/b3ll/Motion/blob/main/Sources/Motion/Utilities/AnimationDriver.swift#L44-L48) and crashing, due to the minimum FPS being greater than the maximum. I'm unsure why iPhone 11 Pro would claim to have a max refresh rate of `61` (perhaps it's something specific to the exact device we're testing with). Would it feasible to change the `adjustedMinFPS` calculation to ensure `maxFPS >= minFPS`?

**Comment by b3ll** [comment]
wow that is such a strange bug, but yeah I can easily add a guard for that

**Comment by b3ll** [comment]
Fix is being released in v0.1.3 :)

**Comment by adamastern** [comment]
Thank you!
