### ISSUE TITLE
Repo's in a weird state / missing `Resources/MotionMovieMaker` in `.gitmodules` ?

### ISSUE THREAD

**Issue by diederich** [b3ll/Motion#27]
Hey Adam!

Just saw that SPM falls over when pulling the latest changes from the repo. It looks like it's getting confused around `Resources/MotionMovieMaker`:

```
 fatal: No url found for submodule path 'Resources/MotionMovieMaker' in .gitmodules
```

Apparently SPM does a `git submodule update --init` when pulling changes, which then bails out.

**Comment by b3ll** [comment]
Oh wow, that’s annoying. I thought I removed that, sorry about that. I’ll have it fixed in a few min!

**Comment by b3ll** [comment]
Ok, just pushed a fix to `main`. Verified it worked locally with some of my other project but let me know if it isn't working for you after running `Update Swift Packages`

**Comment by diederich** [comment]
Thanks for the quick fix @b3ll ! 🙏 
(CI was blocked on this so I switched to our fork. Testing locally works fine again & will switch back to your upstream soon)

**Comment by b3ll** [comment]
apologies 🫠

I dunno how the tests passed locally

**Comment by diederich** [comment]
> apologies 🫠
> 
> I dunno how the tests passed locally

Oh no, don't worry. This was only meant as an excuse for me for not trying it again properly now :-D
