### ISSUE TITLE
[Enhancement] Provide Read-Only `toValue` on `DecayAnimation`

### ISSUE THREAD

**Issue by cdoncarroll** [b3ll/Motion#28]
I've run into a set of use cases for `DecayAnimation` in which knowing the target `toValue` before the animation begins could help drive some other behavior (e.g. custom paging in a scroll view like UI, or fetching new data from the network), but currently `DecayAnimation` provides no public way of accessing this value. Other UI/animation frameworks have included such functionality:

- `UIScrollView` provides this value to its delegate via the `scrollViewWillEndDragging(_:withVelocity:targetContentOffset:)` callback.
- POP provides this value via the `toValue` property on `POPDecayAnimation`. 

Would you consider adding a means for accessing `DecayAnimation`'s internal target value?

**Comment by b3ll** [comment]
Wow, sorry, forgot to respond to this. 

Happy to add that, shouldn't be too bad.

It is useful to note that `DecayAnimation` actually marks `toValue` as unavailable as it doesn't use the value at all, rather it updates `value` as needed until the `velocity` reaches zero. Implementing `toValue` would just involve precomputing where the scroll would scroll to, so I guess that makes sense as an accessor?

**Comment by cdoncarroll** [comment]
Lol. No worries 😅. I actually meant to propose a PR with the change, but haven't been able to get to it yet.

I agree that precomputing the target value, and providing that as a getter would fit what I want nicely.

**Comment by b3ll** [comment]
Should be implemented! Try it out and lmk if it's missing anything
