### ISSUE TITLE
macOS bugs?

### ISSUE THREAD

**Issue by jessegrosjean** [b3ll/Motion#5]
This library looks nice, thanks!

I think the macOS version needs some work though. I'm building a macOS app and I think there are some problems in the CVDisplayLink code that make everything pretty slow and buggy feeling.

The problems:

1. I don't think animations are running long enough or maybe it's they are not getting enough frames. Anyway when I do a 1 second animation I only see about 30 frames. (This is on display that normally shows 60fps). I think this problem is caused by this line:

        let dt = CFTimeInterval(outputTime.pointee.videoTime - currentTime.pointee.videoTime) / CFTimeInterval(outputTime.pointee.videoTimeScale)

    I don't really understand that code, but the `dt` value doesn't seem right. I get what I think are correct results if instead of calculating `dt` that way I calculate it the way the CADisplayLink code is ... by saving into `lastFrameTimestamp` etc. Does it make sense to make the CVDisplayLink path use the same approach?

2. I also think these lines are problematic:

        DispatchQueue.main.async {
            slef.tick(dt)
        }

    A better way is to use DispatchSourceUserDataAdd like in this example: https://gist.github.com/CanTheAlmighty/ee76fbf701a61651fe439fcd6d25f41d

Do these changes make sense to you or am I missing something? I will submit pull request if you think they make sense.

**Comment by b3ll** [comment]
Oh snap, yeah this is definitely a bug, and TIL of `DispatchSourceUserDataAdd`. I'm happy to take a PR, or I can take a look at this later this week. Thank you very much for pointing this out!

**Comment by jessegrosjean** [comment]
Thanks, I've just made a pull request.

**Comment by b3ll** [comment]
Merged
