### ISSUE TITLE
Add a BlockAnimation type?

### ISSUE THREAD

**Issue by jessegrosjean** [b3ll/Motion#7]
I would like a way to get my own code called indefinitely from the Motion animation system.

For example I want to support autoscrolling some content.

To do that I would like to:

1. On mouse down start autoscroll callback
2. Perform autoscroll from Motion animation callback
3. On mouse up stop autoscroll.

I can sort of do this with the existing BasicAnimation class, but it makes my code confusing. I need to set arbitrary values for from/to and use .infinity for duration.

I think a nicer way is to add a new Motion animation type. I'm unsure of name, but here's what I'm currently using:

```
public class BlockAnimation<State>: Animation {

    public var state: State
    
    private let callback: (State) -> State
    
    public init(state: State, callback: @escaping (State) -> State) {
        self.state = state
        self.callback = callback
    }
    
    public override func hasResolved() -> Bool {
        false
    }
    
    public override func tick(frame: AnimationFrame) {
        state = callback(state)
    }

}
```

Using the Animation looks like this:

```
class MyView {
    var autoscrollAnimation: BlockAnimation<Event>?
    
    func mouseDown(event: Event) {
        autoscrollAnimation?.stop()
        autoscrollAnimation = BlockAnimation(state: event) { [weak self] event in
            // autoscroll
            return event
        })
    }
    
    func mouseMoved(event: Event) {
        autoscrollAnimation?.state = event
    }
    
    func mouseUp(event: Event) {
        autoscrollAnimation?.stop()
        autoscrollAnimation = nil
    }
}
```

Is this something that could be added to motion?

**Comment by jessegrosjean** [comment]
Another alternative to adding something like this to Motion would be to open Animation for subclassing outside framework. Either way is OK by me, but I think there should be some way to have client code run in sync with Motion animation loop and not tie that code to a specific duration.

**Comment by b3ll** [comment]
Trying to understand the use-case here more, are you trying to get an animation that just runs on a frame-by-frame tick indefinitely when it's enabled (regardless of any interpolation / resolution on the from/toValue?).

**Comment by jessegrosjean** [comment]
Yes, that's the goal.

**Comment by b3ll** [comment]
Oh neat, okay I'll think about what to call this / how to expose it a bit. Sounds like a good addition to me!
