### ISSUE TITLE
Support for macOS Mojave?

### ISSUE THREAD

**Issue by insidegui** [b3ll/Motion#8]
I've been experimenting with Motion to replace the old POP animation library in my app, but unfortunately I still need to support macOS Mojave.

Looking into the package's implementation, I found almost nothing in there that's not available in Mojave. It seems to use a little bit of Combine but not as a core component or as a major public-facing API. For now, I've made a [fork](https://github.com/insidegui/Motion/tree/mojave-support) (`mojave-support` branch, which I pulled from the branch in #6) that drops the macOS deployment target to 10.14 and removes usage of the unsupported APIs.

This fork has currently been tested in the following OSes/systems:
- [x] macOS Monterey 12.2 beta (Apple Silicon)
- [x] macOS Monterey 12.1 (Apple Silicon)
- [x] macOS Big Sur 11.6.2 (Apple Silicon)
- [x] macOS Catalina 10.15.6 (Intel)
- [x] macOS Mojave 10.14.6 (Intel)

I understand if you don't wish to support all the way back to Mojave, so I'd be happy to just keep using my fork until I can drop support myself, but just thought I'd mention here in case anyone else needs it or you decide to change the minimum deployment target :)

Thanks for creating this amazing library.

**Comment by b3ll** [comment]
oh wow! This is really cool. Thanks for helping out @insidegui.

I think supporting macOS Mojave is totally fine, I just used Combine because it made some things cleaner, but it's by no means a make-or-break. I'd really only consider dropping Mojave if it broke some SIMD perf or limited some animation potential or something like that.

If you've also been able to test the work that @jessegrosjean made with #6 that's an even better candidate to just merge into main anyways. I don't have a lot of macOS targets I can test personally. Have you experienced any deadlocking / frame drops / wonkiness?

**Comment by insidegui** [comment]
Great!

> Have you experienced any deadlocking / frame drops / wonkiness?

I haven't done extensive testing yet, only tested the stuff I'm currently using (`BasicAnimation`/`SpringAnimation`). I can do some additional testing in the future. I'm also likely going to ship this to production in a popular app soon, so we'll definitely learn if there are any edge cases 😅

**Comment by jessegrosjean** [comment]
@insidegui I think my branch is one commit ahead of yours ... pull in that last commit to do testing please. I'm pretty sure (but not positive! :)) threading should be OK in that latest commit. I haven't seen any lockups for a week or so.

**Comment by insidegui** [comment]
> @insidegui I think my branch is one commit ahead of yours ... pull in that last commit to do testing please. I'm pretty sure (but not positive! :)) threading should be OK in that latest commit. I haven't seen any lockups for a week or so.

Thanks for the heads up, just updated my fork to that.

I'll probably only have time to do further testing in a couple of weeks, I'll be sure to pull in any new changes before then.

**Comment by b3ll** [comment]
Okay, I'm just gonna merge in both of these changes, I think it's fine for now. Since anything is better than what I've got for macOS currently 😂

**Comment by b3ll** [comment]
thank you very much both of you for helping!!

**Comment by insidegui** [comment]
FYI AirBuddy 2.5 shipped last week to lots of people and its status windows now use Motion for the animation. No bugs so far, so I think it's safe to assume that it's good to go 😅

I did however encounter some weird behavior during development that only happened on my MacBook Air running Monterey 12.2 beta, and only happened in one particular session (not sure why).

Animations just wouldn't start, and I'm not entirely sure why. Changing `isPaused` to check for the actual state of the display link instead of the `isPaused` property itself fixed it: https://github.com/insidegui/Motion/commit/4e3dd64581cc25b4292d0f4d1e90d107f5857848

**Comment by b3ll** [comment]
Rad, glad to hear! :D 

I'm just fixing up some of the targets that use SwiftUI and won't work on Mojave (i.e. Graphing), and then it should be good to merge

**Comment by b3ll** [comment]
Merged
